apiVersion: v1
kind: Service
metadata:
  name: <APP-NAME>
  labels:
    app: <APP-NAME>
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: <APP-NAME>
  type: LoadBalancer
  loadBalancerIP: 146.148.31.3
  loadBalancerSourceRanges:
  - 0.0.0.0/0